# Generated by Django 5.2.11 on 2026-02-23 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_chatroom_chatmessage_modelsubmission_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок новости')),
                ('image', models.ImageField(upload_to='news_previews/', verbose_name='Превью (картинка)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('content', models.TextField(blank=True, verbose_name='Текст новости')),
            ],
            options={
                'verbose_name': 'Новости',
                'ordering': ['-created_at'],
            },
        ),
    ]
