# Generated by Django 5.2.11 on 2026-03-03 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_newsitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard_number', models.CharField(max_length=100, verbose_name='Номер / Стандарт')),
                ('name', models.CharField(max_length=255, verbose_name='Название документа')),
                ('file', models.FileField(upload_to='documents/', verbose_name='Файл документа')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('downloads_count', models.PositiveIntegerField(default=0, verbose_name='Кол-во скачиваний')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документация',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
