# Generated by Django 5.2.11 on 2026-03-04 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelsubmission',
            name='model_file',
        ),
        migrations.AddField(
            model_name='modelsubmission',
            name='category',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Тип изделия'),
        ),
        migrations.AddField(
            model_name='modelsubmission',
            name='file_igs',
            field=models.FileField(blank=True, null=True, upload_to='submissions/models/igs/', verbose_name='Файл IGS/IGES'),
        ),
        migrations.AddField(
            model_name='modelsubmission',
            name='file_stl',
            field=models.FileField(blank=True, null=True, upload_to='submissions/models/stl/', verbose_name='Файл STL'),
        ),
        migrations.AddField(
            model_name='modelsubmission',
            name='file_stp',
            field=models.FileField(blank=True, null=True, upload_to='submissions/models/stp/', verbose_name='Файл STP/STEP'),
        ),
        migrations.AddField(
            model_name='modelsubmission',
            name='standard',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Стандарт'),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='documents/pdfs/'),
        ),
    ]
