# Generated by Django 5.2.11 on 2026-03-05 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_remove_modelsubmission_model_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='password_changed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
