# Generated by Django 5.2.11 on 2026-03-05 18:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_profile_password_changed_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modelsubmission',
            options={'ordering': ['-created_at'], 'verbose_name': 'Модель', 'verbose_name_plural': 'Модели'},
        ),
        migrations.RemoveField(
            model_name='modelsubmission',
            name='admin_comment',
        ),
        migrations.RemoveField(
            model_name='modelsubmission',
            name='reviewed_at',
        ),
        migrations.RemoveField(
            model_name='modelsubmission',
            name='reviewed_by',
        ),
        migrations.RemoveField(
            model_name='modelsubmission',
            name='status',
        ),
        migrations.RemoveField(
            model_name='modelsubmission',
            name='user',
        ),
        migrations.AlterField(
            model_name='modelsubmission',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='modelsubmission',
            name='file_igs',
            field=models.FileField(blank=True, null=True, upload_to='models/igs/', verbose_name='Файл IGS'),
        ),
        migrations.AlterField(
            model_name='modelsubmission',
            name='file_stl',
            field=models.FileField(blank=True, null=True, upload_to='models/stl/', verbose_name='Файл STL'),
        ),
        migrations.AlterField(
            model_name='modelsubmission',
            name='file_stp',
            field=models.FileField(blank=True, null=True, upload_to='models/stp/', verbose_name='Файл STP'),
        ),
        migrations.AlterField(
            model_name='modelsubmission',
            name='standard',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Стандарт (ГОСТ/ISO)'),
        ),
        migrations.AlterField(
            model_name='modelsubmission',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/', verbose_name='Превью (фото)'),
        ),
        migrations.AlterField(
            model_name='modelsubmission',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название изделия'),
        ),
    ]
