# Generated by Django 5.2.11 on 2026-04-05 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_chatmessage_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelsubmission',
            name='file_amf',
            field=models.FileField(blank=True, null=True, upload_to='models/amf/', verbose_name='Файл AMF'),
        ),
        migrations.AddField(
            model_name='modelsubmission',
            name='file_dwg',
            field=models.FileField(blank=True, null=True, upload_to='models/dwg/', verbose_name='Файл DWG'),
        ),
        migrations.AddField(
            model_name='modelsubmission',
            name='file_obj',
            field=models.FileField(blank=True, null=True, upload_to='models/obj/', verbose_name='Файл OBJ'),
        ),
    ]
