# Generated by Django 5.2.11 on 2026-04-05 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_modelsubmission_file_amf_modelsubmission_file_dwg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='is_drawing',
            field=models.BooleanField(default=False, verbose_name='Это чертеж?'),
        ),
    ]
