upstream django {
    server web:8000;
}

server {
    listen 80;
    
    # Максимальный размер загружаемого файла (важно для 3D моделей!)
    client_max_body_size 100M;

    location / {
        proxy_pass http://django;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
        proxy_redirect off;
    }

    # Раздача статики (CSS, JS, картинки дизайна)
    location /static/ {
        alias /app/staticfiles/;
    }

    # Раздача медиа (аватарки, 3D модели, файлы)
    location /media/ {
        alias /app/media/;
    }
}